config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  devise_for :users

  resources :questions, only: [:index, :show, :new, :create] do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :answers, only: [:create] do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  content     :text
#  question_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  validates :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def voted_by?(user)
    votes.exists?(user: user)
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  content          :text
#  commentable_type :string
#  commentable_id   :integer
#  user_id          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :content, presence: true
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  
  validates :name, :description, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  username               :string
#

class User < ApplicationRecord
  attr_accessor :login
  has_many :questions
  has_many :answers
  has_many :comments
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id           :integer          not null, primary key
#  votable_type :string
#  votable_id   :integer
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(@answer.question_id)

    @answer.save

    if @answer.errors.any?
      render 'questions/show'
    else
      redirect_to @question, notice: "Tu respuesta fue publicada exitosamente"
    end
  end

  private
    def answer_params
      params.require(:answer).permit(:content, :question_id).merge(user: current_user)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if params[:question_id]
      commentable = Question.find(params[:question_id])
      @question = commentable
    elsif params[:answer_id]
      commentable = Answer.find(params[:answer_id])
      @question = Question.find(commentable.question_id)
    end

    @comment = commentable.comments.create(comment_params)

    if @comment.errors.any?
      render 'questions/show'
    else
      redirect_to @question, notice: "Tu comentario fue publicado exitosamente"
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content).merge(user: current_user)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @current_user = current_user
    if params[:search] != nil
      search_key = "%#{params[:search]}%"
      @questions = Question.where('name LIKE ? OR description LIKE ?', search_key, search_key)
    else
      @questions = Question.all
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to question_path(@question), notice: "La pregunta fue publicada exitosamente"
    else
      render :new
    end
  end

  private
    def question_params
      params.require(:question).permit(:name, :description)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    if params[:question_id]
      votable = Question.find(params[:question_id])
      @question = votable
    elsif params[:answer_id]
      votable = Answer.find(params[:answer_id])
      @question = Question.find(votable.question_id)
    end

    votable.votes.create(user: current_user)

    redirect_to @question 
  end

  def destroy
    if params[:question_id]
      votable = Question.find(params[:question_id])
      @question = votable
    elsif params[:answer_id]
      votable = Answer.find(params[:answer_id])
      @question = Question.find(votable.question_id)
    end

    votable.votes.where(user: current_user).take.try(:destroy)

    redirect_to @question 
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowOverstack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Flow Overstack", root_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <%= form_tag questions_path, class: "navbar-form navbar-left", method: :get do %>
              <div class="form.group">
                <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Buscar" %>
              </div>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= user_signed_in? ? current_user.username : "Login" %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to "Registrarme", new_user_registration_path %></li>
                  <li><%= link_to "Ingresar", new_user_session_path %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">

      <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
      
    </div>

  </body>
</html>

app/views/questions/index.html.erb
<h1>Preguntas</h1>

<div>
<%= 
  link_to_if(@current_user.nil?, "Hacer pregunta", new_user_session_path, class: "btn btn-primary btn-lg pull-right") do
    link_to("Hacer pregunta", new_question_path, class: "btn btn-primary btn-lg pull-right")
  end
%>
</div>

<div class="clearfix"></div>

<div class="table-responsive">
  <table class="table">
    <% @questions.each do |question| %>
      <tr>
        <td colspan="1">
          <p class="text-center"><%= question.votes.count %></p>
          <p class="text-center">Votos</p>
        </td>
        <td colspan="1">
          <p class="text-center"><%= question.answers.count %></p>
          <p class="text-center">Respuestas</p>
        </td>
        <td colspan="10">
          <p><%= link_to question.name, question_path(question) %></p>
          <p>por: <%= question.user.email %> <%= question.created_at %></p>
        </td>
      </tr>  
    <% end %>
  </table>
</div>

app/views/questions/new.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">

    <%= render 'layouts/error_messages', object: @question %>
    
    <h1>Preguntar</h1>

    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.text_field :name, class: "form-control", placeholder: "Preguntar" %>
      </div>
      <div class="form-group">
        <%= f.text_area :description, class: "form-control", placeholder: "Descripción", rows: "5" %>
      </div>
      <div>
        <%= f.submit "Preguntar", class: "btn btn-primary pull-right" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row">

<%- # comment form errors -%>
  <% if @comment %>
    <%= render 'layouts/error_messages', object: @comment %>
  <% end %>

<%- # answer form errors -%> 
  <% if @answer %>
    <%= render 'layouts/error_messages', object: @answer %>
  <% end %>

  <h1><%= @question.name %></h1>

<%- # vote question -%>
  <div class="col-sm-1">

<%- # vote question if user is signed in -%>
    <% if user_signed_in? %>
      <% if @question.voted_by? current_user %>
          <%= link_to question_vote_path(@question), method: :delete do %>
            <div class="vote-down">
              <span class="glyphicon glyphicon-chevron-down"></span>
              <%= @question.votes.count %>
            </div> 
          <% end %>
      <% else %>
          <%= link_to question_votes_path(@question), method: :post do %>
            <div class="vote-up">
              <span class="glyphicon glyphicon-chevron-up"></span>
              <%= @question.votes.count %>
            </div>
          <% end %>
      <% end %>

<%- # question's votes count-%>
    <% else %>
      <p><%= @question.votes.count %></p>
    <% end %>
  </div>

<%- # question's description -%>
  <div class="col-sm-11">
    <p><%= @question.description.html_safe %></p>
  </div>
</div>

<%- # question's comments and username -%>
<div class="row">
  <div class="col-sm-11 col-sm-offset-1">
    <% @question.comments.each do |comment| %>
      <div>
        <p><span class="username"><%= comment.user.username %></span> <%= comment.content.html_safe %></p>
      </div>
    <% end %>
  </div>

<%- # comment question -%>
  <div class="col-sm-11 col-sm-offset-1">

<%- # comments' form if user is signed in -%>
    <% if user_signed_in? %>
      <%= form_for [@question, @question.comments.build] do |comment_field| %>
        <div class="form-group">
          <%= comment_field.text_area :content, class: "form-control", placeholder: "Comentario" %>
        </div>
        <div>
          <%= comment_field.submit "Comentar", class: "btn btn-primary pull-right" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>


<div>
  <div>

<%- # queston's answers count -%>
    <h2><%= @question.answers.count %> repuestas:</h2>
    <% @question.answers.each do |answer| %>
      <div class="row">
        <div class="col-sm-1">

<%- # vote answer if user is signed in -%>
          <% if user_signed_in? %>
            <% if answer.voted_by? current_user %>
                <%= link_to answer_vote_path(answer), method: :delete do %>
                  <div class="vote-down">
                    <span class="glyphicon glyphicon-chevron-down"></span>
                    <%= answer.votes.count %>
                  </div>
                <% end %>
            <% else %>
                <%= link_to answer_votes_path(answer), method: :post do %>
                  <div class="vote-up">
                    <span class="glyphicon glyphicon-chevron-up"></span>
                    <%= answer.votes.count %>
                  </div>
                <% end %>
            <% end %>

<%- # answer's votes count -%>
          <% else %>
            <p><%= answer.votes.count %></p>
          <% end %>
        </div>

<%- # answer and username -%>
        <div class="col-sm-11">
          <header><span class="username"><%= answer.user.username %></span></header>
          <p><%= answer.content.html_safe %></p>
        </div>

<%- # answer comment's and username -%>
        <div class="col-sm-11 col-sm-offset-1">
          <% answer.comments.each do |comment| %>
            <p><span class="username"><%= comment.user.username %></span> <%= comment.content.html_safe %></p>
          <% end %>
        </div>

<%- # comment (answer) form if user is signed in -%>
        <div class="col-sm-11 col-sm-offset-1">
          <% if user_signed_in? %>
            <%= form_for [answer, answer.comments.build] do |comment_field| %>
              <div class="form-group">
                <%= comment_field.text_area :content, class: "form-control", placeholder: "Respuesta" %>
              </div>
              <div>
                <%= comment_field.submit "Comentar", class: "btn btn-primary pull-right" %>
              </div>
            <% end %>
          <% end %>
        </div>

      </div>
    <% end %>
  </div>

<%- # answer question if user is signed in -%>
  <div class="col-sm-9">
    <% if user_signed_in? %>
      <h2>Tu respuesta</h2>

      <%= form_for @question.answers.new do |answer_field| %>
        <%= answer_field.hidden_field :question_id, :value => @question.id %>
        <div class="form-group">
          <%= answer_field.text_area :content, class: "form-control", rows: "10", placeholder: "Respuesta" %>
        </div>
        <div>
          <%= answer_field.submit "Responder", class: "btn btn-primary pull-right" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>